on:
  push:
    branches:
      - main
  pull_request:

name: 'Checks'
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn --immutable

      - name: Linting projects
        run: yarn test:lint

  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn --immutable

      - name: Linting projects
        run: yarn test:types
